controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

add_panier:
    path: '/add_panier/{produitsId}'
    controller: 'App\Controller\PanierController::addPanier'

